import { useEffect } from "react";
import { Link, useLocation } from "wouter";
import { ArrowRight, BriefcaseBusiness, Compass, ExternalLink, MessageCircleMore, Network, Radio, UsersRound } from "lucide-react";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import ConnectedNetworkCanvas from "@/components/ConnectedNetworkCanvas";
import HolographicCard from "@/components/HolographicCard";
import WhoAreWeMark from "@/components/WhoAreWeMark";

const ecosystem = [
  { icon: Compass, title: "Your Portal", copy: "A public home for the person, business, community, or idea you want people to understand." },
  { icon: Radio, title: "Your Signals", copy: "Share updates, work, opportunities, and ideas with context—not noise." },
  { icon: UsersRound, title: "Your Connections", copy: "Build relationships around shared interests, purpose, and possibility." },
];

function initials(name: string) { return name.split(" ").filter(Boolean).slice(0, 2).map((word) => word[0]).join("").toUpperCase(); }

export default function Home() {
  const { isAuthenticated, loading } = useAuth();
  const [, navigate] = useLocation();
  const demo = trpc.platform.demo.useQuery();
  const demoProfile = demo.data?.profile;
  const demoPath = demoProfile ? `/${demoProfile.username}` : "/mediarevolution";
  const demoInitials = demoProfile ? initials(demoProfile.displayName) : "MR";

  useEffect(() => { if (!isAuthenticated) return; const nextPath = window.sessionStorage.getItem("whoarewe-post-login"); if (nextPath) { window.sessionStorage.removeItem("whoarewe-post-login"); navigate(nextPath); return; } navigate("/discover"); }, [isAuthenticated, navigate]);
  if (loading || isAuthenticated) return <main className="min-h-screen bg-[#080B14]" />;

  return <main className="page-shell min-h-screen bg-[#080B14] text-white"><div className="grid-noise" /><header className="relative z-20 mx-auto flex max-w-7xl items-center justify-between px-4 py-5 sm:px-6 lg:px-8"><Link href="/" aria-label="WhoAreWe home"><WhoAreWeMark /></Link><nav className="hidden items-center gap-7 text-xs font-bold text-slate-400 md:flex"><Link href="/discover" className="transition hover:text-[#00D8FF]">Discover Portals</Link><a href="#ecosystem" className="transition hover:text-[#00D8FF]">How it works</a><Link href={demoPath} className="transition hover:text-[#00D8FF]">Visit a Portal</Link></nav><div className="flex items-center gap-3"><Link href="/access?next=/account" className="hidden text-xs font-bold text-slate-400 transition hover:text-[#00D8FF] sm:block">Sign In</Link><Link href="/join" className="secondary-button !rounded-full !px-4 !py-2.5 !text-xs">Create Your Portal</Link></div></header>

    <section className="relative z-10 mx-auto grid max-w-7xl gap-12 px-4 pb-20 pt-14 sm:px-6 lg:grid-cols-[1.04fr_.96fr] lg:items-center lg:px-8 lg:pb-28 lg:pt-24"><div className="max-w-2xl"><span className="eyebrow"><span className="signal-dot" /> The Network Behind Who We Are</span><h1 className="font-display mt-6 max-w-3xl text-4xl font-semibold tracking-[-.065em] text-white sm:text-5xl lg:text-[4.55rem] lg:leading-[.98]">More than a profile. <span className="bg-[linear-gradient(105deg,#7CFF38,#00D8FF_36%,#378DFF_66%,#9B4DFF)] bg-clip-text text-transparent">A place for what&apos;s possible.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-slate-400 sm:text-lg">WhoAreWe brings people, businesses, creators, communities, and ideas into a connected presence—so identity creates context and context creates opportunity.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/join" className="primary-button">Create Your Portal <ArrowRight size={16} /></Link><Link href={demoPath} className="secondary-button">Visit a Portal <ExternalLink size={16} /></Link></div><div className="mt-9 flex flex-wrap gap-x-7 gap-y-3 text-xs font-semibold text-slate-500"><span>People</span><span className="text-[#00D8FF]">→</span><span>Businesses</span><span className="text-[#9B4DFF]">→</span><span>Communities</span><span className="text-[#7CFF38]">→</span><span>Opportunity</span></div></div>
      <ConnectedNetworkCanvas nodeCount={28} className="min-h-[410px] sm:min-h-[470px]"><div className="absolute inset-5 rounded-[1.5rem] border border-white/[.09] bg-[linear-gradient(150deg,rgba(19,29,52,.94),rgba(10,15,27,.86))] shadow-[0_28px_80px_rgba(0,0,0,.25)]" /><div className="absolute left-[12%] top-[16%] rounded-full border border-[#7CFF38]/30 bg-[#7CFF38]/10 px-3 py-2 text-[10px] font-extrabold uppercase tracking-[.12em] text-[#C4FF9A]">Identity</div><div className="absolute right-[11%] top-[22%] rounded-full border border-[#00D8FF]/30 bg-[#00D8FF]/10 px-3 py-2 text-[10px] font-extrabold uppercase tracking-[.12em] text-[#9DEFFF]">Connection</div><div className="absolute bottom-[18%] left-[13%] rounded-full border border-[#9B4DFF]/30 bg-[#9B4DFF]/10 px-3 py-2 text-[10px] font-extrabold uppercase tracking-[.12em] text-[#DFBFFF]">Opportunity</div><svg className="absolute inset-0 h-full w-full" viewBox="0 0 600 460" preserveAspectRatio="none" aria-hidden="true"><path d="M112 110 L306 225 L493 128 M306 225 L126 345 M306 225 L475 352" fill="none" stroke="rgba(147,213,245,.28)" strokeWidth="1" strokeDasharray="4 8" /></svg><HolographicCard className="absolute left-1/2 top-1/2 w-[14rem] -translate-x-1/2 -translate-y-1/2 p-5 sm:w-[17rem]"><div className="flex items-start justify-between gap-3"><span className="grid h-11 w-11 place-items-center overflow-hidden rounded-2xl bg-[var(--brand-gradient)] text-sm font-extrabold text-[#08101A]">{demoProfile?.avatarUrl ? <img src={demoProfile.avatarUrl} alt="" className="h-full w-full object-cover" /> : demoInitials}</span><span className="rounded-full border border-white/[.09] bg-white/[.025] px-2 py-1 text-[9px] font-extrabold uppercase tracking-[.11em] text-slate-400">Portal</span></div><p className="font-display mt-7 text-xl font-semibold tracking-[-.05em] text-white">{demoProfile?.displayName || "Media Revolution"}</p><p className="mt-1 text-xs font-semibold text-slate-500">@{demoProfile?.username || "mediarevolution"} · Business</p><p className="mt-4 text-xs leading-5 text-slate-400">A clear identity with places to explore, Signals to follow, and a reason to connect.</p><Link href={demoPath} className="mt-5 inline-flex items-center gap-2 text-xs font-bold text-[#00D8FF]">Visit Portal <ArrowRight size={14} /></Link></HolographicCard></ConnectedNetworkCanvas></section>

    <section id="ecosystem" className="relative z-10 border-y border-white/[.07] bg-[#0B1020]/70"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><div className="grid gap-8 md:grid-cols-[.7fr_1.3fr] md:items-end"><div><span className="eyebrow">Identity first. Network second. Opportunity third.</span><h2 className="font-display mt-5 text-3xl font-semibold tracking-[-.055em] text-white sm:text-4xl">Built for more than a bio.</h2></div><p className="max-w-2xl text-sm leading-7 text-slate-400">WhoAreWe keeps the helpful parts of a profile, professional network, creator space, and community directory—then connects them around purpose rather than endless engagement.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{ecosystem.map(({ icon: Icon, title, copy }, index) => <HolographicCard key={title} className="p-6"><span className="text-[10px] font-extrabold tracking-[.15em] text-slate-600">0{index + 1}</span><span className="mt-9 grid h-11 w-11 place-items-center rounded-xl border border-white/[.1] bg-white/[.035] text-[#00D8FF]"><Icon size={20} /></span><h3 className="font-display mt-5 text-xl font-semibold text-white">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{copy}</p></HolographicCard>)}</div></div></section>

    <section className="relative z-10 mx-auto grid max-w-7xl gap-8 px-4 py-16 sm:px-6 lg:grid-cols-[1fr_.85fr] lg:items-center lg:px-8 lg:py-24"><div><span className="eyebrow"><Compass size={12} /> Discover with context</span><h2 className="font-display mt-5 max-w-2xl text-3xl font-semibold tracking-[-.055em] text-white sm:text-4xl">Discover who people are—and what they bring to the network.</h2><p className="mt-5 max-w-xl text-sm leading-7 text-slate-400">Explore people, businesses, creators, communities, and projects through their Portals. Follow a Signal, connect around shared intent, or find the next place to go.</p><Link href="/discover" className="primary-button mt-7">Discover Portals <Compass size={16} /></Link></div><div className="grid gap-3"><div className="rounded-2xl border border-white/[.09] bg-white/[.025] p-5"><BriefcaseBusiness className="text-[#7CFF38]" size={20} /><p className="font-display mt-4 text-lg font-semibold text-white">Business-ready by design</p><p className="mt-2 text-xs leading-5 text-slate-500">Services, booking links, projects, products, teams, and opportunities can grow as modular Portal content.</p></div><div className="rounded-2xl border border-white/[.09] bg-white/[.025] p-5"><MessageCircleMore className="text-[#9B4DFF]" size={20} /><p className="font-display mt-4 text-lg font-semibold text-white">Intentional participation</p><p className="mt-2 text-xs leading-5 text-slate-500">A Timeline shaped by Portals and Connections you choose—not by attention traps.</p></div></div></section>

    <footer className="relative z-10 border-t border-white/[.07] px-4 py-8 sm:px-6 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-4 text-xs text-slate-500 sm:flex-row sm:items-center sm:justify-between"><WhoAreWeMark tagline /><div className="flex flex-wrap gap-5"><Link href="/discover" className="hover:text-[#00D8FF]">Discover Portals</Link><Link href="/join" className="hover:text-[#00D8FF]">Create Your Portal</Link><Link href={demoPath} className="hover:text-[#00D8FF]">Featured Portal</Link></div></div></footer>
  </main>;
}
