import { Link, useRoute } from "wouter";
import { ArrowLeft, Check, CircleUserRound, Network as NetworkIcon, UserPlus, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";

type NetworkRecord = { relationship: { id: number; type: "follow" | "connection" | "collaborator" | "associated"; status: "pending" | "accepted" | "declined" | "blocked"; createdAt: Date | string; updatedAt: Date | string }; direction: "incoming" | "outgoing"; profile: { id: number; username: string; displayName: string; type: string; bio: string | null; location: string | null } | null };

function initials(name: string) { return name.split(" ").filter(Boolean).slice(0, 2).map((item) => item[0]).join("").toUpperCase(); }

function NetworkCard({ record, accept, accepting }: { record: NetworkRecord; accept?: () => void; accepting?: boolean }) {
  if (!record.profile) return null;
  const action = record.relationship.type === "connection" && record.relationship.status === "pending" && record.direction === "incoming";
  return <article className="rounded-xl border border-white/[.08] bg-white/[.02] p-4"><div className="flex gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-cyan-200/20 bg-gradient-to-br from-cyan-100 via-sky-300 to-violet-400 text-xs font-extrabold text-[#08101A]">{initials(record.profile.displayName)}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><p className="truncate text-sm font-bold text-white">{record.profile.displayName}</p><span className="rounded-full border border-white/[.08] px-2 py-1 text-[9px] font-extrabold uppercase tracking-[.1em] text-slate-500">{record.relationship.status}</span></div><p className="mt-0.5 text-xs font-semibold text-slate-500">@{record.profile.username} · {record.profile.type}</p><p className="mt-2 text-xs leading-5 text-slate-500">{record.profile.bio || "A WhoAreWe identity."}</p>{action && <button disabled={accepting} onClick={accept} className="primary-button mt-3 !px-3 !py-2 !text-xs"><Check size={14} /> {accepting ? "Accepting…" : "Accept Connection"}</button>}{record.relationship.type === "connection" && record.relationship.status === "pending" && record.direction === "outgoing" && <p className="mt-3 text-[10px] font-bold uppercase tracking-[.1em] text-violet-200">Request awaiting a response</p>}</div></div></article>;
}

export default function Network() {
  const { isAuthenticated, loading } = useAuth();
  const [, params] = useRoute("/network/:profileId");
  const profileId = Number(params?.profileId);
  const profile = trpc.profile.builder.useQuery({ profileId }, { enabled: isAuthenticated && Boolean(profileId) });
  const network = trpc.relationships.network.useQuery({ profileId }, { enabled: isAuthenticated && Boolean(profileId) });
  const utils = trpc.useUtils();
  const accept = trpc.relationships.acceptConnection.useMutation({ onSuccess: () => { toast.success("Connection accepted"); utils.relationships.network.invalidate({ profileId }); }, onError: (error) => toast.error(error.message) });

  if (loading) return <main className="min-h-screen bg-[#080B14]" />;
  if (!isAuthenticated) return <main className="grid min-h-screen place-items-center bg-[#080B14] px-4"><div className="max-w-md rounded-3xl border border-white/10 bg-slate-900/60 p-8 text-center"><UsersRound className="mx-auto text-cyan-100" /><h1 className="font-display mt-5 text-2xl font-semibold text-white">Your intentional Network</h1><p className="mt-3 text-sm leading-6 text-slate-400">Sign in to manage the people and Profiles connected to your identity.</p><button onClick={() => startLogin()} className="primary-button mt-7 w-full">Sign in to continue</button></div></main>;
  if (profile.isLoading || network.isLoading) return <main className="min-h-screen bg-[#080B14] p-10 text-sm font-bold text-slate-500">Loading Network…</main>;
  if (!profile.data || !network.data) return <main className="grid min-h-screen place-items-center bg-[#080B14] px-4 text-white"><div className="text-center"><p className="font-display text-2xl font-semibold">Profile not found</p><Link href="/onboarding" className="primary-button mt-6">Create a Profile</Link></div></main>;

  const records = network.data as NetworkRecord[];
  const incoming = records.filter((record) => record.relationship.type === "connection" && record.relationship.status === "pending" && record.direction === "incoming");
  const connections = records.filter((record) => record.relationship.type === "connection" && record.relationship.status === "accepted");
  const following = records.filter((record) => record.relationship.type === "follow" && record.relationship.status === "accepted");
  return <main className="min-h-screen bg-[#080B14] text-white"><header className="sticky top-0 z-30 border-b border-white/[.07] bg-[#080B14]/85 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4 sm:px-6"><div className="flex items-center gap-3"><Link href={`/builder/${profileId}`} className="flex items-center gap-2 text-xs font-bold text-slate-400 transition hover:text-cyan-100"><ArrowLeft size={14} /> Portal Builder</Link><span className="h-4 w-px bg-white/10" /><span className="font-display text-sm font-semibold text-white">Network</span></div><Link href={`/${profile.data.profile.username}`} target="_blank" className="secondary-button !px-3 !py-2.5 !text-xs">View Profile</Link></div></header>
    <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:py-12"><span className="eyebrow"><span className="signal-dot" /> Intentional relationships</span><div className="mt-5 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="font-display text-3xl font-semibold tracking-[-.055em] text-white">Your Network, not your audience.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-500">Followers are one-way. Connections are mutual. Both belong to this Profile—not the Account behind it.</p></div><div className="flex gap-2"><span className="rounded-xl border border-white/[.08] bg-white/[.02] px-3 py-2 text-xs font-bold text-slate-400">{connections.length} Connections</span><span className="rounded-xl border border-white/[.08] bg-white/[.02] px-3 py-2 text-xs font-bold text-slate-400">{following.length} Following</span></div></div>
      <div className="mt-8 grid gap-6 lg:grid-cols-3"><section><div className="flex items-center justify-between"><h2 className="font-display text-lg font-semibold text-white">Requests</h2><span className="rounded-full bg-violet-300/10 px-2 py-1 text-[10px] font-extrabold text-violet-200">{incoming.length}</span></div><div className="mt-3 space-y-3">{incoming.map((record) => <NetworkCard key={record.relationship.id} record={record} accepting={accept.isPending} accept={() => accept.mutate({ profileId, relationshipId: record.relationship.id })} />)}{incoming.length === 0 && <div className="rounded-xl border border-dashed border-white/[.12] p-6 text-center"><UserPlus className="mx-auto text-slate-600" size={20} /><p className="mt-3 text-xs font-bold text-slate-500">No pending requests</p></div>}</div></section><section><div className="flex items-center justify-between"><h2 className="font-display text-lg font-semibold text-white">Connections</h2><span className="rounded-full bg-cyan-300/10 px-2 py-1 text-[10px] font-extrabold text-cyan-100">{connections.length}</span></div><div className="mt-3 space-y-3">{connections.map((record) => <NetworkCard key={record.relationship.id} record={record} />)}{connections.length === 0 && <div className="rounded-xl border border-dashed border-white/[.12] p-6 text-center"><NetworkIcon className="mx-auto text-slate-600" size={20} /><p className="mt-3 text-xs font-bold text-slate-500">Connections will appear here.</p></div>}</div></section><section><div className="flex items-center justify-between"><h2 className="font-display text-lg font-semibold text-white">Following</h2><span className="rounded-full bg-white/[.04] px-2 py-1 text-[10px] font-extrabold text-slate-400">{following.length}</span></div><div className="mt-3 space-y-3">{following.map((record) => <NetworkCard key={record.relationship.id} record={record} />)}{following.length === 0 && <div className="rounded-xl border border-dashed border-white/[.12] p-6 text-center"><CircleUserRound className="mx-auto text-slate-600" size={20} /><p className="mt-3 text-xs font-bold text-slate-500">Follow Profiles you want in your Timeline.</p></div>}</div></section></div>
    </div></main>;
}
