import { useMemo, useState } from "react";
import { Link, useLocation } from "wouter";
import { ArrowLeft, ArrowRight, Check, ChevronLeft, Globe2, Link2, Plus, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";
import NeuralAccessLogin from "@/components/ui/neural-access-login";
import WhoAreWeMark from "@/components/WhoAreWeMark";
import { trpc } from "@/lib/trpc";
import { INTERESTS, type InterestKey } from "@shared/interests";

const profileTypes = [
  ["personal", "Personal", "For the person behind the story."],
  ["business", "Business", "For a company, studio, service, or brand."],
  ["creator", "Creator", "For creative work, an independent voice, or a practice."],
  ["organization", "Community", "For a group, collective, non-profit, or shared cause."],
  ["project", "Project", "For a product, initiative, event, or idea in motion."],
] as const;
type ProfileType = (typeof profileTypes)[number][0];
type Destination = { id: number; title: string; url: string };
const steps = ["Who are you?", "Name your Portal", "Add your first destinations"];

export default function Onboarding() {
  const { isAuthenticated, loading } = useAuth();
  const [, navigate] = useLocation();
  const [step, setStep] = useState(0);
  const [displayName, setDisplayName] = useState("");
  const [username, setUsername] = useState("");
  const [type, setType] = useState<ProfileType>("personal");
  const [bio, setBio] = useState("");
  const [location, setLocation] = useState("");
  const [interests, setInterests] = useState<InterestKey[]>([]);
  const [destinations, setDestinations] = useState<Destination[]>([{ id: 1, title: "", url: "" }]);
  const existingProfiles = trpc.profile.my.useQuery(undefined, { enabled: isAuthenticated });
  const capacity = trpc.profile.capacity.useQuery(undefined, { enabled: isAuthenticated });
  const createNode = trpc.profile.createNode.useMutation();
  const createProfile = trpc.profile.create.useMutation({ onError: (error) => toast.error(error.message) });
  const isBusy = createProfile.isPending || createNode.isPending;
  const hasExistingPortal = Boolean(existingProfiles.data?.length);
  const isAdditionalPortal = new URLSearchParams(window.location.search).get("additional") === "1";
  const capacityReached = Boolean(capacity.data && !capacity.data.canCreate);
  const capacityLabel = capacity.data?.status === "free" ? `Free early access: ${capacity.data.used} of ${capacity.data.allowance} Portals in use` : `Portal capacity: ${capacity.data?.used ?? 0} of ${capacity.data?.allowance ?? 3} in use`;
  const filledDestinations = useMemo(() => destinations.filter((destination) => destination.title.trim() && destination.url.trim()), [destinations]);
  const updateDestination = (id: number, updates: Partial<Destination>) => setDestinations((current) => current.map((destination) => destination.id === id ? { ...destination, ...updates } : destination));
  const next = () => {
    if (step === 1 && (!displayName.trim() || !username.trim())) { toast.error("Add a name and Portal handle to continue."); return; }
    setStep((current) => Math.min(2, current + 1));
  };
  const submit = async () => {
    try {
      const profile = await createProfile.mutateAsync({ username, displayName, type, bio: bio || undefined, location: location || undefined, interests });
      const positions = [[20, 27], [79, 31], [21, 72], [78, 72]];
      await Promise.all(filledDestinations.map((destination, index) => createNode.mutateAsync({ profileId: profile.id, type: "web", title: destination.title.trim(), targetUrl: destination.url.trim(), positionX: positions[index % positions.length][0], positionY: positions[index % positions.length][1] })));
      toast.success("Your Portal is ready to shape.");
      navigate(`/builder/${profile.id}`);
    } catch { /* Mutations surface a clear toast. */ }
  };
  if (loading) return <main className="min-h-screen bg-[#080B14]" />;
  if (!isAuthenticated) return <NeuralAccessLogin nextPath="/onboarding" mode="create" />;
  if (hasExistingPortal && !isAdditionalPortal) return <main className="min-h-screen bg-[#080B14] px-4 py-8 text-white sm:px-6"><div className="mx-auto max-w-xl rounded-[1.5rem] border border-white/[.1] bg-[#0B1020] p-7 text-center shadow-[0_24px_70px_rgba(0,0,0,.25)]"><WhoAreWeMark className="justify-center" /><Sparkles className="mx-auto mt-8 text-[#7CFF38]" size={24} /><h1 className="font-display mt-4 text-3xl font-semibold tracking-[-.055em]">Your Portal is already waiting.</h1><p className="mt-4 text-sm leading-6 text-slate-400">Open it to add destinations, publish Signals, and grow your Connections—or create another Portal for a distinct part of your world.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row sm:justify-center"><Link href={`/builder/${existingProfiles.data?.[0]?.id}`} className="primary-button">Open Your Portal <ArrowRight size={16} /></Link><Link href="/onboarding?additional=1" className="secondary-button"><Plus size={15} /> New identity</Link><Link href="/account" className="secondary-button">My Portals</Link></div></div></main>;
  if (isAdditionalPortal && capacityReached) return <main className="min-h-screen bg-[#080B14] px-4 py-8 text-white sm:px-6"><div className="mx-auto max-w-xl rounded-[1.5rem] border border-white/[.1] bg-[#0B1020] p-7 text-center shadow-[0_24px_70px_rgba(0,0,0,.25)]"><WhoAreWeMark className="justify-center" /><Sparkles className="mx-auto mt-8 text-[#9B4DFF]" size={24} /><h1 className="font-display mt-4 text-3xl font-semibold tracking-[-.055em]">Your Portal network is full for now.</h1><p className="mt-4 text-sm leading-6 text-slate-400">Early access includes up to {capacity.data?.allowance ?? 3} Portals. Keep shaping your existing identities and link them together from any Portal Builder.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row sm:justify-center"><Link href="/account" className="primary-button">My Portals <ArrowRight size={16} /></Link><Link href="/discover" className="secondary-button">Discover</Link></div></div></main>;

  return <main className="min-h-screen bg-[#080B14] text-white"><header className="border-b border-white/[.07] bg-[#080B14]/88 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4 sm:px-6"><Link href="/discover" className="flex items-center gap-2 text-xs font-bold text-slate-400 transition hover:text-[#00D8FF]"><ArrowLeft size={14} /> Discover</Link><WhoAreWeMark label={false} /><Link href="/account" className="text-xs font-bold text-slate-400 transition hover:text-[#00D8FF]">My Portals</Link></div></header><div className="mx-auto grid max-w-6xl gap-10 px-4 py-10 sm:px-6 lg:grid-cols-[.78fr_1.22fr] lg:py-18"><aside className="lg:sticky lg:top-10 lg:h-fit"><span className="eyebrow"><span className="signal-dot" /> {isAdditionalPortal ? "New identity" : "Create your Portal"}</span><h1 className="font-display mt-5 text-4xl font-semibold tracking-[-.065em] text-white">{isAdditionalPortal ? "Give another part of your world its own Portal." : "A clear start for what you want people to discover."}</h1><p className="mt-5 max-w-md text-sm leading-7 text-slate-400">{isAdditionalPortal ? "This Portal can stand on its own, then become a connected destination in the larger map of your identities." : "Your Portal can represent a person, business, creator, community, or project. It grows with your identity—one meaningful connection at a time."}</p><p className="mt-4 text-xs font-bold text-[#BFFF93]">{capacityLabel}</p><div className="mt-9 space-y-4 border-l border-white/[.11] pl-5">{steps.map((label, index) => <div key={label} className={index === step ? "text-white" : index < step ? "text-[#7CFF38]" : "text-slate-600"}><p className="text-[10px] font-extrabold uppercase tracking-[.14em]">0{index + 1}</p><p className="mt-1 text-sm font-bold">{label}</p></div>)}</div></aside><section className="rounded-[1.5rem] border border-white/[.1] bg-[linear-gradient(145deg,rgba(18,28,50,.93),rgba(9,14,25,.96))] p-5 shadow-[0_25px_70px_rgba(0,0,0,.24)] sm:p-8"><div className="flex items-center justify-between border-b border-white/[.08] pb-5"><div><p className="text-[10px] font-extrabold uppercase tracking-[.14em] text-[#00D8FF]">Step {step + 1} of 3 · {isAdditionalPortal ? "New identity" : "First Portal"}</p><h2 className="font-display mt-2 text-2xl font-semibold tracking-[-.05em]">{steps[step]}</h2></div><span className="grid h-10 w-10 place-items-center rounded-xl border border-white/[.1] bg-white/[.035] text-[#9B4DFF]">{step === 0 ? <Sparkles size={18} /> : step === 1 ? <Globe2 size={18} /> : <Link2 size={18} />}</span></div>
    {step === 0 && <div className="mt-7"><p className="text-sm font-bold text-slate-200">What does this Portal represent?</p><p className="mt-1 text-xs leading-5 text-slate-500">Choose the clearest starting point. You can add Nodes and Connections around it afterward.</p><div className="mt-5 grid gap-2 sm:grid-cols-2">{profileTypes.map(([value, label, description]) => <button type="button" key={value} onClick={() => setType(value)} className={`rounded-xl border p-4 text-left transition ${type === value ? "border-[#00D8FF]/45 bg-[#00D8FF]/[.075]" : "border-white/[.08] bg-white/[.02] hover:border-white/20"}`}><span className="flex items-center justify-between text-sm font-bold text-white">{label}{type === value && <Check size={15} className="text-[#7CFF38]" />}</span><span className="mt-2 block text-xs leading-5 text-slate-500">{description}</span></button>)}</div><div className="mt-7 border-t border-white/[.08] pt-6"><div className="flex items-center justify-between"><p className="text-xs font-bold text-slate-300">What brings you here? <span className="font-medium text-slate-600">optional</span></p><span className="text-[10px] text-slate-600">{interests.length}/6</span></div><p className="mt-1.5 text-xs leading-5 text-slate-500">These private preferences help surface relevant Portals and follow suggestions. They never appear on your public Portal.</p><div className="mt-3 flex flex-wrap gap-2">{INTERESTS.map((interest) => { const selected = interests.includes(interest.key); const unavailable = !selected && interests.length >= 6; return <button key={interest.key} disabled={unavailable} type="button" onClick={() => setInterests((current) => selected ? current.filter((key) => key !== interest.key) : [...current, interest.key])} className={`rounded-full border px-3 py-2 text-[11px] font-bold transition disabled:opacity-35 ${selected ? "border-[#9B4DFF]/45 bg-[#9B4DFF]/[.11] text-[#E3C9FF]" : "border-white/[.09] bg-white/[.02] text-slate-400 hover:text-slate-200"}`}>{selected && <Check size={12} className="mr-1 inline" />}{interest.label}</button>; })}</div></div></div>}
    {step === 1 && <div className="mt-7"><p className="text-sm font-bold text-slate-200">Give your Portal a name people will recognize.</p><p className="mt-1 text-xs leading-5 text-slate-500">This can be your name, business, community, project, or creative practice.</p><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="text-xs font-bold text-slate-300">Display name<input required value={displayName} onChange={(event) => setDisplayName(event.target.value)} placeholder={type === "business" ? "North Star Studio" : "Your name"} className="mt-2 h-11 w-full rounded-xl border border-white/10 bg-slate-950/50 px-3 text-sm text-white outline-none placeholder:text-slate-600 focus:border-[#00D8FF]/50" /></label><label className="text-xs font-bold text-slate-300">Portal handle<div className="mt-2 flex h-11 items-center rounded-xl border border-white/10 bg-slate-950/50 px-3 focus-within:border-[#00D8FF]/50"><span className="text-sm font-bold text-slate-500">@</span><input required value={username} onChange={(event) => setUsername(event.target.value.replace(/^@/, "").replace(/\s/g, ""))} placeholder="yourportal" className="min-w-0 flex-1 bg-transparent pl-1 text-sm text-white outline-none placeholder:text-slate-600" /></div><span className="mt-1.5 block text-[10px] font-medium text-slate-600">Letters, numbers, and underscores only.</span></label><label className="text-xs font-bold text-slate-300 sm:col-span-2">Short introduction <span className="font-medium text-slate-600">optional</span><textarea value={bio} onChange={(event) => setBio(event.target.value)} rows={3} placeholder="A sentence about what this Portal is here to share, build, or offer." className="mt-2 w-full resize-none rounded-xl border border-white/10 bg-slate-950/50 px-3 py-3 text-sm leading-6 text-white outline-none placeholder:text-slate-600 focus:border-[#00D8FF]/50" /></label><label className="text-xs font-bold text-slate-300">Location <span className="font-medium text-slate-600">optional</span><input value={location} onChange={(event) => setLocation(event.target.value)} placeholder="Toronto, Canada" className="mt-2 h-11 w-full rounded-xl border border-white/10 bg-slate-950/50 px-3 text-sm text-white outline-none placeholder:text-slate-600 focus:border-[#00D8FF]/50" /></label></div></div>}
    {step === 2 && <div className="mt-7"><p className="text-sm font-bold text-slate-200">Add your first places to go.</p><p className="mt-1 text-xs leading-5 text-slate-500">Website, newsletter, booking page, store, service, or any custom link. You can add more once the Portal opens.</p><div className="mt-5 space-y-3">{destinations.map((destination, index) => <div key={destination.id} className="rounded-xl border border-white/[.08] bg-white/[.02] p-3"><div className="flex items-center justify-between"><p className="text-[10px] font-extrabold uppercase tracking-[.13em] text-[#00D8FF]">Destination {index + 1}</p>{destinations.length > 1 && <button type="button" onClick={() => setDestinations((current) => current.filter((item) => item.id !== destination.id))} className="text-[10px] font-bold text-slate-500 hover:text-white">Remove</button>}</div><div className="mt-3 grid gap-3 sm:grid-cols-[.8fr_1.2fr]"><input value={destination.title} onChange={(event) => updateDestination(destination.id, { title: event.target.value })} placeholder="Website, Booking, Store…" className="h-10 rounded-lg border border-white/10 bg-slate-950/55 px-3 text-xs text-white outline-none placeholder:text-slate-600 focus:border-[#00D8FF]/50" /><input value={destination.url} onChange={(event) => updateDestination(destination.id, { url: event.target.value })} placeholder="https://…" className="h-10 rounded-lg border border-white/10 bg-slate-950/55 px-3 text-xs text-white outline-none placeholder:text-slate-600 focus:border-[#00D8FF]/50" /></div></div>)}</div>{destinations.length < 3 && <button type="button" onClick={() => setDestinations((current) => [...current, { id: Date.now(), title: "", url: "" }])} className="mt-3 inline-flex items-center gap-2 text-xs font-bold text-[#00D8FF] hover:text-white"><Plus size={14} /> Add another destination</button>}<div className="mt-6 rounded-xl border border-[#7CFF38]/18 bg-[#7CFF38]/[.045] p-4 text-xs leading-5 text-slate-400"><span className="font-bold text-[#BFFF93]">You&apos;re in control.</span> You can skip this for now and build out your map in the Portal Builder instead.</div></div>}
    <div className="mt-8 flex flex-col-reverse gap-3 border-t border-white/[.08] pt-5 sm:flex-row sm:justify-between">{step > 0 ? <button type="button" onClick={() => setStep((current) => current - 1)} className="secondary-button !px-4 !py-2.5 !text-xs"><ChevronLeft size={15} /> Back</button> : <Link href="/account" className="secondary-button !px-4 !py-2.5 !text-xs">Save for later</Link>}{step < 2 ? <button type="button" onClick={next} className="primary-button !px-4 !py-2.5 !text-xs">Continue <ArrowRight size={15} /></button> : <button type="button" disabled={isBusy || !displayName.trim() || !username.trim()} onClick={submit} className="primary-button !px-4 !py-2.5 !text-xs disabled:cursor-not-allowed disabled:opacity-50">{isBusy ? "Creating…" : "Create Your Portal"} <ArrowRight size={15} /></button>}</div></section></div></main>;
}
