import { type CSSProperties, type PointerEvent as ReactPointerEvent, type TouchEvent as ReactTouchEvent, useEffect, useMemo, useRef, useState } from "react";
import { ArrowUpRight, Bolt, CalendarCheck2, CalendarDays, ChevronDown, Compass, Gem, Globe2, Leaf, Link2, Mail, Maximize2, Minimize2, Minus, Move, Music2, Orbit, RotateCcw, ShoppingBag, Sparkles, UsersRound, Video, ZoomIn } from "lucide-react";
import ConnectedNetworkCanvas from "./ConnectedNetworkCanvas";

type NodeCategory = "identity" | "social" | "web" | "content" | "conversion" | "portal" | "event" | "product" | "booking" | "team";
type LiveConnection = { fromNodeId: number; toNodeId: number };
type LinkedPortal = { id: number; username: string; displayName: string; type: string; bio: string | null; location: string | null; avatarUrl: string | null; isPublished: boolean; nodes: LiveNode[]; connections: LiveConnection[] };
type LiveNode = { id: number; type: NodeCategory; title: string; subtitle: string | null; description: string | null; targetUrl: string | null; internalProfileId: number | null; portalRelationshipType?: "related" | "brand" | "team" | "project" | "community" | "location" | null; portalRelationshipLabel?: string | null; accentColor?: string | null; positionX: number; positionY: number; linkedPortal?: LinkedPortal | null };
type LiveProfile = { displayName: string; username: string; type: string; bio: string | null; location: string | null; mapAccentColor?: string | null; mapIcon?: string | null; mapAutoFocusNext?: boolean | null };
type MapSelection = { key: string; title: string; kind: string; summary: string; targetUrl: string | null; icon: typeof Sparkles; focusX: number; focusY: number };

const typeIcons: Record<NodeCategory, typeof Sparkles> = { identity: UsersRound, social: Globe2, web: Link2, content: Video, conversion: Mail, portal: Compass, event: CalendarDays, product: ShoppingBag, booking: CalendarCheck2, team: UsersRound };
const MIN_ZOOM = .45;
const MAX_ZOOM = 1.35;
const clampZoom = (value: number) => Math.max(MIN_ZOOM, Math.min(MAX_ZOOM, value));
const clampPan = (value: number, max: number) => Math.max(-max, Math.min(max, value));
const initials = (name: string) => name.split(" ").filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase();
const relationshipLabel = (node: LiveNode) => node.portalRelationshipLabel || ({ related: "Related identity", brand: "Brand family", team: "Team space", project: "Project space", community: "Community space", location: "Location space" }[node.portalRelationshipType || "related"]);
const mapIcons: Record<string, typeof Sparkles> = { spark: Sparkles, orbit: Orbit, bolt: Bolt, gem: Gem, leaf: Leaf };

function DetailContent({ selected, onClose, mobile = false }: { selected: MapSelection; onClose: () => void; mobile?: boolean }) {
  const Icon = selected.icon;
  return <><div className="flex items-start justify-between gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-cyan-200/20 bg-cyan-300/10 text-cyan-100"><Icon size={19} strokeWidth={1.8} /></span><div className="min-w-0 flex-1"><p className="text-[9px] font-extrabold uppercase tracking-[.13em] text-cyan-100">Selected destination</p><p className="font-display mt-1 truncate text-lg font-semibold tracking-tight text-white">{selected.title}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[.11em] text-slate-500">{selected.kind}</p></div><button type="button" onClick={onClose} aria-label="Close map detail" className="grid h-8 w-8 shrink-0 place-items-center rounded-full border border-white/10 bg-white/[.04] text-slate-400 transition hover:bg-white/[.08] hover:text-white"><ChevronDown size={17} /></button></div><p className="mt-3 text-xs leading-5 text-slate-300">{selected.summary}</p><div className="mt-4 flex items-center gap-2">{selected.targetUrl ? <a href={selected.targetUrl} className="primary-button flex-1 !px-3 !py-2.5 !text-xs">Open Portal <ArrowUpRight size={14} /></a> : <span className="flex-1 rounded-lg border border-white/[.08] bg-white/[.025] px-3 py-2.5 text-center text-[10px] font-bold text-slate-400">Explore a connected destination</span>}<button type="button" onClick={onClose} className="secondary-button !px-3 !py-2.5 !text-xs">{mobile ? "Map" : "Close"}</button></div></>;
}

export default function LivePortalGraph({ profile, nodes, connections, onNodeOpen }: { profile: LiveProfile; nodes: LiveNode[]; connections: LiveConnection[]; onNodeOpen?: (nodeId: number) => void }) {
  const stageRef = useRef<HTMLDivElement>(null);
  const worldRef = useRef<HTMLDivElement>(null);
  const touchGestureRef = useRef<{ distance: number; centerX: number; centerY: number; zoom: number; panX: number; panY: number } | null>(null);
  const pointerPanRef = useRef<{ pointerId: number; x: number; y: number; panX: number; panY: number } | null>(null);
  const autoFocusKeyRef = useRef<string | null>(null);
  const viewRef = useRef({ zoom: 1, pan: { x: 0, y: 0 } });
  const rootSelection = (): MapSelection => ({ key: "root", title: profile.displayName, kind: `${profile.type}${profile.location ? ` · ${profile.location}` : ""}`, summary: profile.bio || "A public identity built to be explored.", targetUrl: null, icon: Sparkles, focusX: 50, focusY: 50 });
  const [selected, setSelected] = useState<MapSelection>(rootSelection);
  const [isDetailOpen, setIsDetailOpen] = useState(false);
  const [activeRegion, setActiveRegion] = useState(0);
  const [regionTrail, setRegionTrail] = useState<number[]>([0]);
  const [relationshipFilter, setRelationshipFilter] = useState<"all" | "project" | "team" | "community">("all");
  const [isRegionTransition, setIsRegionTransition] = useState(false);
  const [touchStartY, setTouchStartY] = useState<number | null>(null);
  const [zoom, setZoom] = useState(1);
  const [pan, setPan] = useState({ x: 0, y: 0 });
  const [isSwitcherOpen, setIsSwitcherOpen] = useState(false);
  const [isFullscreen, setIsFullscreen] = useState(() => new URLSearchParams(window.location.search).get("network") === "full");
  const [showGestureHint, setShowGestureHint] = useState(false);
  const nodeLookup = useMemo(() => new Map(nodes.map((node) => [node.id, node])), [nodes]);
  const allLinkedRegions = useMemo(() => nodes.filter((node) => node.type === "portal" && node.linkedPortal).map((node, index) => ({ node, portal: node.linkedPortal!, regionX: 150 + index * 100 })), [nodes]);
  const linkedRegions = useMemo(() => relationshipFilter === "all" ? allLinkedRegions : allLinkedRegions.filter((region) => region.node.portalRelationshipType === relationshipFilter), [allLinkedRegions, relationshipFilter]);
  const RootIcon = mapIcons[profile.mapIcon || "spark"] || Sparkles;
  const mapAccent = profile.mapAccentColor || "#00D8FF";
  const zoomPercent = Math.round(zoom * 100);

  useEffect(() => { setSelected(rootSelection()); setIsDetailOpen(false); setActiveRegion(0); setRegionTrail([0]); }, [profile.displayName, profile.bio, profile.location, profile.type]);
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === "Escape") { setIsDetailOpen(false); setIsSwitcherOpen(false); setIsFullscreen(false); } }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, []);
  useEffect(() => { if (!isFullscreen) return; const originalOverflow = document.body.style.overflow; document.body.style.overflow = "hidden"; return () => { document.body.style.overflow = originalOverflow; }; }, [isFullscreen]);
  useEffect(() => { try { setShowGestureHint(!window.localStorage.getItem("whoarewe-map-gesture-guide-v1")); } catch { setShowGestureHint(false); } }, []);

  const applyView = (nextZoom: number, nextPan: { x: number; y: number }) => { viewRef.current = { zoom: nextZoom, pan: nextPan }; if (worldRef.current) worldRef.current.style.transform = `translate(${nextPan.x / 3}%, ${nextPan.y}%) scale(${nextZoom})`; };
  const setManipulating = (active: boolean) => worldRef.current?.classList.toggle("is-manipulating", active);
  const commitView = () => { setZoom(viewRef.current.zoom); setPan(viewRef.current.pan); };
  const openSelection = (next: MapSelection, trackNodeId?: number) => { const same = selected.key === next.key; setSelected(next); setIsDetailOpen((open) => same ? !open : true); if (trackNodeId && (!same || !isDetailOpen)) onNodeOpen?.(trackNodeId); };
  const focusPortal = (regionIndex: number) => { const region = linkedRegions[regionIndex]; if (!region) return; const regionId = region.portal.id; setIsSwitcherOpen(false); setActiveRegion(regionId); setRegionTrail((trail) => trail[trail.length - 1] === regionId ? trail : [...trail, regionId]); setIsRegionTransition(true); window.setTimeout(() => setIsRegionTransition(false), 420); applyView(1, { x: -(allLinkedRegions.findIndex((item) => item.portal.id === regionId) + 1) * 100, y: 0 }); setZoom(1); setPan({ x: -(allLinkedRegions.findIndex((item) => item.portal.id === regionId) + 1) * 100, y: 0 }); setSelected({ key: `portal-${region.portal.id}`, title: region.portal.displayName, kind: relationshipLabel(region.node), summary: region.portal.bio || `Continue into ${region.portal.displayName} and its connected destinations.`, targetUrl: `/${region.portal.username}`, icon: Compass, focusX: region.regionX, focusY: 50 }); setIsDetailOpen(false); };
  const dismissOnSwipe = (event: ReactTouchEvent<HTMLDivElement>) => { const endY = event.changedTouches[0]?.clientY; if (touchStartY !== null && endY && endY - touchStartY > 52) setIsDetailOpen(false); setTouchStartY(null); };
  const touchDistance = (event: ReactTouchEvent<HTMLDivElement>) => { const [first, second] = [event.touches[0], event.touches[1]]; return first && second ? Math.hypot(second.clientX - first.clientX, second.clientY - first.clientY) : 0; };
  const touchCenter = (event: ReactTouchEvent<HTMLDivElement>) => { const [first, second] = [event.touches[0], event.touches[1]]; return first && second ? { x: (first.clientX + second.clientX) / 2, y: (first.clientY + second.clientY) / 2 } : null; };
  const startTouchGesture = (event: ReactTouchEvent<HTMLDivElement>) => { if (event.touches.length !== 2) return; const center = touchCenter(event); if (!center) return; event.preventDefault(); pointerPanRef.current = null; const current = viewRef.current; setManipulating(true); touchGestureRef.current = { distance: touchDistance(event), centerX: center.x, centerY: center.y, zoom: current.zoom, panX: current.pan.x, panY: current.pan.y }; };
  const moveTouchGesture = (event: ReactTouchEvent<HTMLDivElement>) => { const start = touchGestureRef.current; const bounds = stageRef.current?.getBoundingClientRect(); const center = touchCenter(event); if (!start || !bounds || !center || event.touches.length !== 2) return; event.preventDefault(); applyView(clampZoom(start.zoom * (touchDistance(event) / start.distance)), { x: clampPan(start.panX + ((center.x - start.centerX) / bounds.width) * 100, 220), y: clampPan(start.panY + ((center.y - start.centerY) / bounds.height) * 100, 42) }); };
  const endTouchGesture = (event: ReactTouchEvent<HTMLDivElement>) => { if (event.touches.length < 2 && touchGestureRef.current) { touchGestureRef.current = null; setManipulating(false); commitView(); } };
  const startPointerPan = (event: ReactPointerEvent<HTMLDivElement>) => { if ((event.pointerType !== "mouse" && event.pointerType !== "touch") || (event.pointerType === "touch" && !isFullscreen) || pointerPanRef.current || (event.target as HTMLElement).closest("button,a,input,select,textarea")) return; const current = viewRef.current; pointerPanRef.current = { pointerId: event.pointerId, x: event.clientX, y: event.clientY, panX: current.pan.x, panY: current.pan.y }; event.currentTarget.setPointerCapture(event.pointerId); if (event.pointerType === "touch") event.preventDefault(); setManipulating(true); };
  const movePointerPan = (event: ReactPointerEvent<HTMLDivElement>) => { const start = pointerPanRef.current; const bounds = stageRef.current?.getBoundingClientRect(); if (!start || !bounds || start.pointerId !== event.pointerId) return; if (event.pointerType === "touch") event.preventDefault(); applyView(viewRef.current.zoom, { x: clampPan(start.panX + ((event.clientX - start.x) / bounds.width) * 100, 220), y: clampPan(start.panY + ((event.clientY - start.y) / bounds.height) * 100, 42) }); };
  const endPointerPan = (event: ReactPointerEvent<HTMLDivElement>) => { if (!pointerPanRef.current || pointerPanRef.current.pointerId !== event.pointerId) return; pointerPanRef.current = null; setManipulating(false); commitView(); };
  const moveZoom = (direction: -1 | 1) => { const next = clampZoom(viewRef.current.zoom + direction * .14); applyView(next, viewRef.current.pan); setZoom(next); };
  const resetView = () => { applyView(1, { x: 0, y: 0 }); setIsSwitcherOpen(false); setActiveRegion(0); setRegionTrail([0]); setZoom(1); setPan({ x: 0, y: 0 }); setSelected(rootSelection()); setIsDetailOpen(false); };
  const worldPosition = (regionX: number, node: LiveNode) => ({ left: `${(regionX + (node.positionX - 50)) / 3}%`, top: `${node.positionY}%` } as CSSProperties);
  const localPosition = (node: LiveNode) => worldPosition(50, node);
  const dismissGestureHint = () => { try { window.localStorage.setItem("whoarewe-map-gesture-guide-v1", "seen"); } catch {} setShowGestureHint(false); };

  useEffect(() => {
    const stage = stageRef.current;
    if (!stage) return;
    const handleWheel = (event: WheelEvent) => {
      if ((event.target as HTMLElement).closest("button,a,input,select,textarea")) return;
      event.preventDefault();
      const next = clampZoom(viewRef.current.zoom * (event.deltaY > 0 ? .91 : 1.09));
      applyView(next, viewRef.current.pan);
      setZoom(next);
    };
    stage.addEventListener("wheel", handleWheel, { passive: false });
    return () => stage.removeEventListener("wheel", handleWheel);
  }, [profile.username]);

  useEffect(() => {
    if (!profile.mapAutoFocusNext || allLinkedRegions.length === 0 || autoFocusKeyRef.current === profile.username) return;
    autoFocusKeyRef.current = profile.username;
    const timer = window.setTimeout(() => focusPortal(0), 280);
    return () => window.clearTimeout(timer);
  }, [profile.username, profile.mapAutoFocusNext, allLinkedRegions.length]);

  return <div className="w-full"><div ref={stageRef} className={isFullscreen ? "portal-map-shell is-fullscreen" : "portal-map-shell"} onPointerDown={startPointerPan} onPointerMove={movePointerPan} onPointerUp={endPointerPan} onPointerCancel={endPointerPan} onTouchStart={startTouchGesture} onTouchMove={moveTouchGesture} onTouchEnd={endTouchGesture}><ConnectedNetworkCanvas nodeCount={30 + linkedRegions.length * 10} className={`portal-stage portal-stage--interactive has-map-focus ${isFullscreen ? "portal-stage--fullscreen" : ""}`}> 
    <div className="portal-map-kicker absolute left-5 top-5 z-10 flex items-center gap-2 rounded-full border border-white/10 bg-slate-950/50 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400 backdrop-blur-md"><span style={{ background: mapAccent, boxShadow: `0 0 10px ${mapAccent}` }} className="h-1.5 w-1.5 rounded-full" />{linkedRegions.length ? "Connected Portal map" : "Live identity map"}</div>
    {isFullscreen && <div className="portal-full-network-bar lg:hidden"><div><span>Full network</span><strong>{activeRegion === 0 ? profile.displayName : allLinkedRegions.find((region) => region.portal.id === activeRegion)?.portal.displayName}</strong></div><button type="button" onClick={() => { setIsFullscreen(false); setIsSwitcherOpen(false); }} aria-label="Minimize full network"><Minimize2 size={17} /><span>Minimize</span></button></div>}
    {allLinkedRegions.length > 0 && <div className="portal-map-filter" aria-label="Filter connected Portal map"><span>Show</span>{(["all", "project", "team", "community"] as const).map((filter) => <button key={filter} type="button" onClick={() => { setRelationshipFilter(filter); resetView(); }} className={relationshipFilter === filter ? "is-active" : ""}>{filter === "all" ? "All" : filter === "community" ? "Communities" : `${filter[0].toUpperCase()}${filter.slice(1)}s`}</button>)}</div>}
    <div className="portal-map-breadcrumb" aria-label="Portal map path"><span>Viewing</span>{regionTrail.map((regionId, index) => { const region = regionId === 0 ? null : allLinkedRegions.find((item) => item.portal.id === regionId); const label = region?.portal.displayName || profile.displayName; return <button key={`${regionId}-${index}`} type="button" onClick={() => region ? focusPortal(linkedRegions.findIndex((item) => item.portal.id === region.portal.id)) : resetView()}>{index ? <i>›</i> : null}{label}</button>; })}</div>
    <div className="map-control-cluster absolute right-3 top-3 z-20 flex items-center gap-1 rounded-xl border border-white/10 bg-slate-950/70 p-1 backdrop-blur-md"><span className="hidden max-w-28 truncate px-2 text-[9px] font-extrabold uppercase tracking-[.1em] text-cyan-100 sm:inline">You are viewing {activeRegion === 0 ? profile.displayName : allLinkedRegions.find((item) => item.portal.id === activeRegion)?.portal.displayName}</span><button aria-label="Zoom out" onClick={() => moveZoom(-1)} disabled={zoom <= MIN_ZOOM} className="grid h-8 w-8 place-items-center rounded-lg text-slate-300 hover:bg-white/[.08] disabled:opacity-35"><Minus size={15} /></button><span className="min-w-8 text-center text-[9px] font-extrabold tabular-nums text-slate-400">{zoomPercent}%</span><button aria-label="Zoom in" onClick={() => moveZoom(1)} disabled={zoom >= MAX_ZOOM} className="grid h-8 w-8 place-items-center rounded-lg text-slate-300 hover:bg-white/[.08] disabled:opacity-35"><ZoomIn size={15} /></button><button aria-label="Return to this Portal" onClick={resetView} className="grid h-8 w-8 place-items-center rounded-lg text-slate-300 hover:bg-white/[.08]"><RotateCcw size={14} /></button></div>
    <span className="absolute bottom-4 left-4 z-10 hidden items-center gap-1.5 rounded-full border border-white/[.09] bg-slate-950/55 px-2.5 py-1 text-[9px] font-bold text-slate-500 backdrop-blur-md lg:flex"><Move size={12} /> Scroll to zoom · drag the canvas to pan</span>{isFullscreen && showGestureHint && <div className="portal-map-gesture-hint lg:hidden" role="status"><span className="portal-map-gesture-hint__icon"><Move size={15} /></span><p><strong>Explore the map</strong><span>Drag with one finger. Pinch to zoom.</span></p><button type="button" onClick={dismissGestureHint}>Got it</button></div>}
    {nodes.length === 0 && <p className="absolute inset-x-7 bottom-12 z-10 max-w-xs text-xs font-medium leading-6 text-slate-400">This Portal is published and ready. Add connected Nodes in the Portal Builder to bring this identity map to life.</p>}
    {linkedRegions.length > 0 && <><div className="connected-portal-nav connected-portal-nav--desktop"><p>Connected Portals</p><div><button type="button" onClick={resetView} className={activeRegion === 0 ? "is-active map-home" : "map-home"} aria-label={`Return to ${profile.displayName}`}><span>{initials(profile.displayName)}</span><strong>{activeRegion === 0 ? profile.displayName : `Back to ${profile.displayName}`}<small>{activeRegion === 0 ? "Main Portal" : "Return to the root map"}</small></strong></button>{linkedRegions.map((region, index) => <button key={region.portal.id} type="button" onClick={() => focusPortal(index)} className={selected.key === `portal-${region.portal.id}` ? "is-active" : ""}><span>{initials(region.portal.displayName)}</span><strong>{region.portal.displayName}<small>{relationshipLabel(region.node)}</small></strong></button>)}</div></div><button type="button" className="portal-switcher-trigger" onClick={() => setIsSwitcherOpen((open) => !open)} aria-expanded={isSwitcherOpen} aria-controls="portal-switcher-drawer"><Compass size={14} /> <span>{activeRegion === 0 ? "Portals" : allLinkedRegions.find((region) => region.portal.id === activeRegion)?.portal.displayName}</span><small>{allLinkedRegions.length + 1}</small><ChevronDown size={14} className={isSwitcherOpen ? "rotate-180" : ""} /></button><div id="portal-switcher-drawer" className={`portal-switcher-drawer ${isSwitcherOpen ? "is-open" : ""}`} aria-hidden={!isSwitcherOpen}><div className="portal-switcher-drawer__header"><span>Navigate Portals</span><button type="button" onClick={() => setIsSwitcherOpen(false)} aria-label="Close Portal switcher"><ChevronDown size={16} /></button></div><button type="button" onClick={resetView} className={activeRegion === 0 ? "is-active" : ""}><span>{initials(profile.displayName)}</span><strong>{profile.displayName}<small>Main Portal</small></strong></button>{linkedRegions.map((region, index) => <button key={region.portal.id} type="button" onClick={() => focusPortal(index)} className={activeRegion === region.portal.id ? "is-active" : ""}><span>{initials(region.portal.displayName)}</span><strong>{region.portal.displayName}<small>{relationshipLabel(region.node)}</small></strong></button>)}</div></>}{linkedRegions.length > 0 && <div className="portal-map-minimap" aria-label="Portal map regions"><button type="button" aria-label={`Focus ${profile.displayName}`} onClick={resetView} className={activeRegion === 0 ? "is-active" : ""}><span>{initials(profile.displayName)}</span><i /></button>{linkedRegions.map((region, index) => <button key={region.portal.id} type="button" aria-label={`Focus ${region.portal.displayName}`} onClick={() => focusPortal(index)} className={activeRegion === region.portal.id ? "is-active" : ""}><span>{initials(region.portal.displayName)}</span><i /></button>)}</div>}
    <div ref={worldRef} className={`connected-portal-world ${isRegionTransition ? "is-region-transition" : ""}`} style={{ transform: `translate(${pan.x / 3}%, ${pan.y}%) scale(${zoom})` }}><svg className="graph-lines connected-portal-lines" viewBox="0 0 300 100" preserveAspectRatio="none" aria-hidden="true"><line x1="50" y1="50" x2="50" y2="50" />{nodes.map((node) => <line key={`root-${node.id}`} x1="50" y1="50" x2={node.positionX} y2={node.positionY} />)}{connections.map((connection) => { const from = nodeLookup.get(connection.fromNodeId); const to = nodeLookup.get(connection.toNodeId); return from && to ? <line key={`${connection.fromNodeId}-${connection.toNodeId}`} x1={from.positionX} y1={from.positionY} x2={to.positionX} y2={to.positionY} className="muted" /> : null; })}{linkedRegions.map((region) => <g key={`region-${region.portal.id}`}><line className="portal-hop" x1={region.node.positionX} y1={region.node.positionY} x2={region.regionX} y2="50" />{region.portal.nodes.map((node) => <line key={`remote-root-${region.portal.id}-${node.id}`} x1={region.regionX} y1="50" x2={region.regionX + node.positionX - 50} y2={node.positionY} />)}{region.portal.connections.map((connection) => { const from = region.portal.nodes.find((node) => node.id === connection.fromNodeId); const to = region.portal.nodes.find((node) => node.id === connection.toNodeId); return from && to ? <line className="muted" key={`remote-${region.portal.id}-${connection.fromNodeId}-${connection.toNodeId}`} x1={region.regionX + from.positionX - 50} y1={from.positionY} x2={region.regionX + to.positionX - 50} y2={to.positionY} /> : null; })}</g>)}</svg>
      <span aria-hidden="true" className={`map-focus-orb ${isDetailOpen ? "is-active" : ""}`} style={{ left: `${selected.focusX / 3}%`, top: `${selected.focusY}%` }} />
      <button type="button" aria-label={`Open ${profile.displayName}`} onClick={() => openSelection(rootSelection())} style={{ left: `${50 / 3}%`, top: "50%", borderColor: mapAccent, boxShadow: `0 0 28px ${mapAccent}3d` } as CSSProperties} className={`portal-node portal-node--root ${selected.key === "root" ? "is-active" : ""}`}><span className="portal-node__icon" style={{ color: mapAccent }}><RootIcon size={18} /></span><span className="portal-node__copy"><span className="portal-node__label">{profile.displayName}</span><span className="portal-node__kind">{profile.type}{profile.location ? ` · ${profile.location}` : ""}</span></span></button>
      {nodes.map((node) => { const Icon = typeIcons[node.type]; const next: MapSelection = { key: `local-${node.id}`, title: node.title, kind: node.type === "portal" ? relationshipLabel(node) : node.subtitle || node.type, summary: node.description || "A connected part of this identity.", targetUrl: node.linkedPortal ? `/${node.linkedPortal.username}` : node.targetUrl, icon: Icon, focusX: node.positionX, focusY: node.positionY }; return <button key={node.id} type="button" aria-label={`Open ${node.title}`} onClick={() => openSelection(next, node.id)} style={{ ...localPosition(node), borderColor: node.accentColor || undefined, boxShadow: node.accentColor ? `0 0 24px ${node.accentColor}2b` : undefined } as CSSProperties} className={`portal-node ${selected.key === next.key ? "is-active" : ""}`}><span className="portal-node__icon">{node.type === "content" && node.title.toLowerCase().includes("music") ? <Music2 size={16} strokeWidth={1.9} /> : <Icon size={16} strokeWidth={1.9} />}</span><span className="portal-node__copy"><span className="portal-node__label">{node.title}</span><span className="portal-node__kind">{node.linkedPortal ? relationshipLabel(node) : node.subtitle || node.type}</span></span></button>; })}
      {linkedRegions.map((region, index) => <div key={region.portal.id}><button type="button" aria-label={`Explore ${region.portal.displayName}`} onClick={() => focusPortal(index)} style={{ left: `${region.regionX / 3}%`, top: "50%" } as CSSProperties} className={`portal-node portal-node--root connected-portal-root ${selected.key === `portal-${region.portal.id}` ? "is-active" : ""}`}><span className="portal-node__icon">{region.portal.avatarUrl ? <img src={region.portal.avatarUrl} alt="" className="h-full w-full rounded-full object-cover" /> : initials(region.portal.displayName)}</span><span className="portal-node__copy"><span className="portal-node__label">{region.portal.displayName}</span><span className="portal-node__kind">Connected Portal</span></span></button>{region.portal.nodes.map((node) => { const Icon = typeIcons[node.type]; const next: MapSelection = { key: `remote-${region.portal.id}-${node.id}`, title: node.title, kind: node.subtitle || node.type, summary: node.description || `A destination inside ${region.portal.displayName}.`, targetUrl: node.targetUrl, icon: Icon, focusX: region.regionX + node.positionX - 50, focusY: node.positionY }; return <button key={node.id} type="button" aria-label={`Open ${node.title} in ${region.portal.displayName}`} onClick={() => openSelection(next)} style={{ ...worldPosition(region.regionX, node), borderColor: node.accentColor || undefined } as CSSProperties} className={`portal-node ${selected.key === next.key ? "is-active" : ""}`}><span className="portal-node__icon"><Icon size={16} /></span><span className="portal-node__copy"><span className="portal-node__label">{node.title}</span><span className="portal-node__kind">{node.subtitle || node.type}</span></span></button>; })}</div>)}
    </div>
    <div className={`mobile-node-overlay lg:hidden ${isDetailOpen ? "is-open" : ""}`} aria-hidden={!isDetailOpen}><div className="mobile-node-overlay__pulse" aria-hidden="true" /><div className="mobile-node-overlay__surface" onTouchStart={(event) => setTouchStartY(event.touches[0]?.clientY ?? null)} onTouchEnd={dismissOnSwipe}><div className="mobile-node-overlay__drag-handle" aria-hidden="true" /><DetailContent selected={selected} onClose={() => setIsDetailOpen(false)} mobile /></div></div>
    <div className={`desktop-node-overlay ${isDetailOpen ? "is-open" : ""}`} aria-hidden={!isDetailOpen}><div className="desktop-node-overlay__pulse" aria-hidden="true" /><div className="desktop-node-overlay__surface"><DetailContent selected={selected} onClose={() => setIsDetailOpen(false)} /></div></div>
  </ConnectedNetworkCanvas>{!isFullscreen && <button type="button" onClick={() => setIsFullscreen(true)} className="mobile-full-network-launcher lg:hidden"><span><Maximize2 size={16} /></span><strong>Show full network</strong><small>{allLinkedRegions.length + 1} Portals</small></button>}</div></div>;
}
