import { type CSSProperties, type PointerEvent as ReactPointerEvent, type TouchEvent as ReactTouchEvent, useEffect, useMemo, useRef, useState } from "react";
import { ArrowUpRight, CalendarCheck2, CalendarDays, ChevronDown, Globe2, Link2, Mail, Minus, Move, Music2, RotateCcw, ShoppingBag, Sparkles, UsersRound, Video, ZoomIn } from "lucide-react";
import ConnectedNetworkCanvas from "./ConnectedNetworkCanvas";

type NodeCategory = "identity" | "social" | "web" | "content" | "conversion" | "portal" | "event" | "product" | "booking" | "team";
type LiveNode = { id: number; type: NodeCategory; title: string; subtitle: string | null; description: string | null; targetUrl: string | null; accentColor?: string | null; positionX: number; positionY: number; };
type LiveConnection = { fromNodeId: number; toNodeId: number };
type LiveProfile = { displayName: string; username: string; type: string; bio: string | null; location: string | null };
type Selection = { title: string; kind: string; summary: string; targetUrl: string | null; icon: typeof Sparkles };

const typeIcons: Record<NodeCategory, typeof Sparkles> = { identity: UsersRound, social: Globe2, web: Link2, content: Video, conversion: Mail, portal: Sparkles, event: CalendarDays, product: ShoppingBag, booking: CalendarCheck2, team: UsersRound };
const MIN_ZOOM = .5;
const MAX_ZOOM = 1.35;
const clampZoom = (value: number) => Math.max(MIN_ZOOM, Math.min(MAX_ZOOM, value));
const clampPan = (value: number, max: number) => Math.max(-max, Math.min(max, value));
function firstInitials(name: string) { return name.split(" ").filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase(); }

function DetailContent({ selected, onClose, mobile = false }: { selected: Selection; onClose: () => void; mobile?: boolean }) {
  const Icon = selected.icon;
  return <><div className="flex items-start justify-between gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-cyan-200/20 bg-cyan-300/10 text-cyan-100"><Icon size={19} strokeWidth={1.8} /></span><div className="min-w-0 flex-1"><p className="text-[9px] font-extrabold uppercase tracking-[.13em] text-cyan-100">Selected Node</p><p className="font-display mt-1 truncate text-lg font-semibold tracking-tight text-white">{selected.title}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[.11em] text-slate-500">{selected.kind}</p></div><button type="button" onClick={onClose} aria-label="Close Node detail" className="grid h-8 w-8 shrink-0 place-items-center rounded-full border border-white/10 bg-white/[.04] text-slate-400 transition hover:bg-white/[.08] hover:text-white"><ChevronDown size={17} /></button></div><p className="mt-3 text-xs leading-5 text-slate-300">{selected.summary}</p><div className="mt-4 flex items-center gap-2">{selected.targetUrl ? <a href={selected.targetUrl} target="_blank" rel="noreferrer" className="primary-button flex-1 !px-3 !py-2.5 !text-xs">Open link <ArrowUpRight size={14} /></a> : <span className="flex-1 rounded-lg border border-white/[.08] bg-white/[.025] px-3 py-2.5 text-center text-[10px] font-bold text-slate-400">Explore another Node</span>}<button type="button" onClick={onClose} className="secondary-button !px-3 !py-2.5 !text-xs">{mobile ? "Map" : "Close"}</button></div></>;
}

export default function LivePortalGraph({ profile, nodes, connections, onNodeOpen }: { profile: LiveProfile; nodes: LiveNode[]; connections: LiveConnection[]; onNodeOpen?: (nodeId: number) => void }) {
  const stageRef = useRef<HTMLDivElement>(null);
  const worldRef = useRef<HTMLDivElement>(null);
  const touchGestureRef = useRef<{ distance: number; centerX: number; centerY: number; zoom: number; panX: number; panY: number } | null>(null);
  const pointerPanRef = useRef<{ pointerId: number; x: number; y: number; panX: number; panY: number } | null>(null);
  const viewRef = useRef({ zoom: 1, pan: { x: 0, y: 0 } });
  const [selectedId, setSelectedId] = useState<number | "root">("root");
  const [isDetailOpen, setIsDetailOpen] = useState(false);
  const [touchStartY, setTouchStartY] = useState<number | null>(null);
  const [zoom, setZoom] = useState(1);
  const [pan, setPan] = useState({ x: 0, y: 0 });
  const selectedNode = nodes.find((node) => node.id === selectedId);
  const selected: Selection = selectedNode ? { title: selectedNode.title, kind: selectedNode.subtitle || selectedNode.type, summary: selectedNode.description || "A connected part of this identity.", targetUrl: selectedNode.targetUrl, icon: typeIcons[selectedNode.type] } : { title: profile.displayName, kind: `${profile.type} ${profile.location ? `· ${profile.location}` : ""}`, summary: profile.bio || "A public identity built to be explored.", targetUrl: null, icon: Sparkles };
  const focusPosition = selectedNode ? { x: selectedNode.positionX, y: selectedNode.positionY } : { x: 50, y: 50 };
  const nodeLookup = useMemo(() => new Map(nodes.map((node) => [node.id, node])), [nodes]);
  const zoomPercent = Math.round(zoom * 100);

  const applyView = (nextZoom: number, nextPan: { x: number; y: number }) => { viewRef.current = { zoom: nextZoom, pan: nextPan }; if (worldRef.current) worldRef.current.style.transform = `translate(${nextPan.x}%, ${nextPan.y}%) scale(${nextZoom})`; };
  const setManipulating = (active: boolean) => worldRef.current?.classList.toggle("is-manipulating", active);
  const commitView = () => { setZoom(viewRef.current.zoom); setPan(viewRef.current.pan); };
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === "Escape") setIsDetailOpen(false); }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, []);
  const openNode = (id: number | "root") => { const sameNode = selectedId === id; setSelectedId(id); setIsDetailOpen((wasOpen) => sameNode ? !wasOpen : true); if (typeof id === "number" && (!sameNode || !isDetailOpen)) onNodeOpen?.(id); };
  const dismissOnSwipe = (event: ReactTouchEvent<HTMLDivElement>) => { const endY = event.changedTouches[0]?.clientY; if (touchStartY !== null && endY && endY - touchStartY > 52) setIsDetailOpen(false); setTouchStartY(null); };
  const touchDistance = (event: ReactTouchEvent<HTMLDivElement>) => { const [first, second] = [event.touches[0], event.touches[1]]; return first && second ? Math.hypot(second.clientX - first.clientX, second.clientY - first.clientY) : 0; };
  const touchCenter = (event: ReactTouchEvent<HTMLDivElement>) => { const [first, second] = [event.touches[0], event.touches[1]]; return first && second ? { x: (first.clientX + second.clientX) / 2, y: (first.clientY + second.clientY) / 2 } : null; };
  const startTouchGesture = (event: ReactTouchEvent<HTMLDivElement>) => { if (event.touches.length !== 2) return; const center = touchCenter(event); if (!center) return; event.preventDefault(); const current = viewRef.current; setManipulating(true); touchGestureRef.current = { distance: touchDistance(event), centerX: center.x, centerY: center.y, zoom: current.zoom, panX: current.pan.x, panY: current.pan.y }; };
  const moveTouchGesture = (event: ReactTouchEvent<HTMLDivElement>) => { const start = touchGestureRef.current; const bounds = stageRef.current?.getBoundingClientRect(); const center = touchCenter(event); if (!start || !bounds || !center || event.touches.length !== 2) return; event.preventDefault(); applyView(clampZoom(start.zoom * (touchDistance(event) / start.distance)), { x: clampPan(start.panX + ((center.x - start.centerX) / bounds.width) * 100, 45), y: clampPan(start.panY + ((center.y - start.centerY) / bounds.height) * 100, 42) }); };
  const endTouchGesture = (event: ReactTouchEvent<HTMLDivElement>) => { if (event.touches.length < 2 && touchGestureRef.current) { touchGestureRef.current = null; setManipulating(false); commitView(); } };
  const startPointerPan = (event: ReactPointerEvent<HTMLDivElement>) => { if (event.pointerType !== "mouse" || (event.target as HTMLElement).closest("button,a,input,select,textarea")) return; const current = viewRef.current; pointerPanRef.current = { pointerId: event.pointerId, x: event.clientX, y: event.clientY, panX: current.pan.x, panY: current.pan.y }; event.currentTarget.setPointerCapture(event.pointerId); setManipulating(true); };
  const movePointerPan = (event: ReactPointerEvent<HTMLDivElement>) => { const start = pointerPanRef.current; const bounds = stageRef.current?.getBoundingClientRect(); if (!start || !bounds || start.pointerId !== event.pointerId) return; applyView(viewRef.current.zoom, { x: clampPan(start.panX + ((event.clientX - start.x) / bounds.width) * 100, 45), y: clampPan(start.panY + ((event.clientY - start.y) / bounds.height) * 100, 42) }); };
  const endPointerPan = (event: ReactPointerEvent<HTMLDivElement>) => { if (!pointerPanRef.current || pointerPanRef.current.pointerId !== event.pointerId) return; pointerPanRef.current = null; setManipulating(false); commitView(); };
  const moveZoom = (direction: -1 | 1) => { const next = clampZoom(viewRef.current.zoom + direction * .14); applyView(next, viewRef.current.pan); setZoom(next); };
  const resetView = () => { applyView(1, { x: 0, y: 0 }); setZoom(1); setPan({ x: 0, y: 0 }); };
  const zoomWithWheel = (event: React.WheelEvent<HTMLDivElement>) => { if ((event.target as HTMLElement).closest("button,a,input,select,textarea")) return; event.preventDefault(); const next = clampZoom(viewRef.current.zoom * (event.deltaY > 0 ? .91 : 1.09)); applyView(next, viewRef.current.pan); setZoom(next); };

  return <div className="w-full"><div ref={stageRef} onPointerDown={startPointerPan} onPointerMove={movePointerPan} onPointerUp={endPointerPan} onPointerCancel={endPointerPan} onWheel={zoomWithWheel} onTouchStart={startTouchGesture} onTouchMove={moveTouchGesture} onTouchEnd={endTouchGesture}><ConnectedNetworkCanvas nodeCount={30} className="portal-stage portal-stage--interactive has-map-focus">
    <div className="absolute left-5 top-5 z-10 flex items-center gap-2 rounded-full border border-white/10 bg-slate-950/50 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400 backdrop-blur-md"><span className="h-1.5 w-1.5 rounded-full bg-cyan-300 shadow-[0_0_10px_#77e6fb]" />Live identity map</div>
    <div className="absolute right-3 top-3 z-20 flex items-center gap-1 rounded-xl border border-white/10 bg-slate-950/70 p-1 backdrop-blur-md"><button aria-label="Zoom out" onClick={() => moveZoom(-1)} disabled={zoom <= MIN_ZOOM} className="grid h-8 w-8 place-items-center rounded-lg text-slate-300 hover:bg-white/[.08] disabled:opacity-35"><Minus size={15} /></button><span className="min-w-8 text-center text-[9px] font-extrabold tabular-nums text-slate-400">{zoomPercent}%</span><button aria-label="Zoom in" onClick={() => moveZoom(1)} disabled={zoom >= MAX_ZOOM} className="grid h-8 w-8 place-items-center rounded-lg text-slate-300 hover:bg-white/[.08] disabled:opacity-35"><ZoomIn size={15} /></button><button aria-label="Reset map view" onClick={resetView} className="grid h-8 w-8 place-items-center rounded-lg text-slate-300 hover:bg-white/[.08]"><RotateCcw size={14} /></button></div>
    <span className="absolute bottom-4 left-4 z-10 flex items-center gap-1.5 rounded-full border border-white/[.09] bg-slate-950/55 px-2.5 py-1 text-[9px] font-bold text-slate-500 backdrop-blur-md"><Move size={12} /> <span className="lg:hidden">Pinch to zoom · two fingers to pan</span><span className="hidden lg:inline">Scroll to zoom · drag the canvas to pan</span></span>
    {nodes.length === 0 && <p className="absolute inset-x-7 bottom-12 z-10 max-w-xs text-xs font-medium leading-6 text-slate-400">This Portal is published and ready. Add connected Nodes in the Portal Builder to bring this identity map to life.</p>}
    <div ref={worldRef} className="graph-editor-world" style={{ transform: `translate(${pan.x}%, ${pan.y}%) scale(${zoom})` }}><svg className="graph-lines" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">{nodes.map((node) => <line key={`root-${node.id}`} x1="50" y1="50" x2={node.positionX} y2={node.positionY} />)}{connections.map((connection) => { const from = nodeLookup.get(connection.fromNodeId); const to = nodeLookup.get(connection.toNodeId); return from && to ? <line key={`${connection.fromNodeId}-${connection.toNodeId}`} x1={from.positionX} y1={from.positionY} x2={to.positionX} y2={to.positionY} className="muted" /> : null; })}{nodes.length > 0 && <circle className="graph-pulse" r="0.8"><animateMotion dur="5.5s" repeatCount="indefinite" path={`M50,50 L${nodes[0].positionX},${nodes[0].positionY}`} /></circle>}</svg><span aria-hidden="true" className={`map-focus-orb ${isDetailOpen ? "is-active" : ""}`} style={{ left: `${focusPosition.x}%`, top: `${focusPosition.y}%` }} /><button type="button" aria-pressed={selectedId === "root"} aria-expanded={selectedId === "root" && isDetailOpen} aria-label={`Open ${profile.displayName}`} onClick={() => openNode("root")} style={{ left: "50%", top: "50%" } as CSSProperties} className={`portal-node portal-node--root ${selectedId === "root" ? "is-active" : ""}`}><span className="portal-node__icon">{firstInitials(profile.displayName)}</span><span className="portal-node__copy"><span className="portal-node__label">{profile.displayName}</span><span className="portal-node__kind">{profile.type}{profile.location ? ` · ${profile.location}` : ""}</span></span></button>{nodes.map((node) => { const Icon = typeIcons[node.type]; return <button key={node.id} type="button" aria-pressed={selectedId === node.id} aria-expanded={selectedId === node.id && isDetailOpen} aria-label={`Open ${node.title}`} onClick={() => openNode(node.id)} style={{ left: `${node.positionX}%`, top: `${node.positionY}%`, borderColor: node.accentColor || undefined, boxShadow: node.accentColor ? `0 0 24px ${node.accentColor}2b` : undefined } as CSSProperties} className={`portal-node ${selectedId === node.id ? "is-active" : ""}`}><span className="portal-node__icon">{node.type === "content" && node.title.toLowerCase().includes("music") ? <Music2 size={16} strokeWidth={1.9} /> : <Icon size={16} strokeWidth={1.9} />}</span><span className="portal-node__copy"><span className="portal-node__label">{node.title}</span><span className="portal-node__kind">{node.subtitle || (node.type === "portal" ? "Portal" : node.type)}</span></span></button>; })}</div>
    <div className={`mobile-node-overlay lg:hidden ${isDetailOpen ? "is-open" : ""}`} aria-hidden={!isDetailOpen}><div className="mobile-node-overlay__pulse" aria-hidden="true" /><div className="mobile-node-overlay__surface" onTouchStart={(event) => setTouchStartY(event.touches[0]?.clientY ?? null)} onTouchEnd={dismissOnSwipe}><div className="mobile-node-overlay__drag-handle" aria-hidden="true" /><DetailContent selected={selected} onClose={() => setIsDetailOpen(false)} mobile /></div></div>
    <div className={`desktop-node-overlay ${isDetailOpen ? "is-open" : ""}`} aria-hidden={!isDetailOpen}><div className="desktop-node-overlay__pulse" aria-hidden="true" /><div className="desktop-node-overlay__surface"><DetailContent selected={selected} onClose={() => setIsDetailOpen(false)} /></div></div>
  </ConnectedNetworkCanvas></div></div>;
}
